name: blog-publish-github-action
on: [push, workflow_dispatch]
jobs:
  devto-blog-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Cross Platform Blog Publish
        uses: aru31/blog-publish-action@1.0.0
        with:
          website: "devto"
          log_level: "info"
          token: ${{ secrets.DEVTO_TOKEN }}
